import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { validateImport } from './library'

// The file is generated by `npm run migrate:legacy` and is not committed (it is a personal list).
const file = path.resolve(__dirname, '../../migration/blockbuster-collection.json')

describe.skipIf(!fs.existsSync(file))('legacy migration output', () => {
  const data = JSON.parse(fs.readFileSync(file, 'utf8'))
  const check = validateImport(data)

  it('is a valid import with nothing dropped', () => {
    expect(check.ok).toBe(true)
    if (check.ok) expect(check.dropped).toBe(0)
  })

  it('has stable, unique ids', () => {
    if (!check.ok) throw new Error('invalid')
    const ids = check.items.map((i) => i.id)
    expect(new Set(ids).size).toBe(ids.length)
    expect(ids.every((id) => id.startsWith('legacy-'))).toBe(true)
  })

  it('keeps binder pages and slots, and moves Prime titles to digital', () => {
    if (!check.ok) throw new Error('invalid')
    const binder = check.items.filter((i) => i.location === 'Main binder')
    expect(binder.length).toBeGreaterThan(300)
    expect(binder.every((i) => /^Page \d+( · [A-Z])?$/.test(i.position ?? ''))).toBe(true)
    const prime = check.items.filter((i) => i.location === 'Prime Video')
    expect(prime.length).toBeGreaterThan(300)
    expect(prime.every((i) => i.format === 'digital')).toBe(true)
  })

  it('turns the old abbreviations and suffixes into proper fields', () => {
    if (!check.ok) throw new Error('invalid')
    const hp = check.items.find((i) => i.title === "Harry Potter: The Sorcerer's Stone" && i.edition)
    expect(hp).toMatchObject({ series: 'Harry Potter', seriesNum: '1', edition: 'Special features disc', format: 'dvd' })
    expect(check.items.some((i) => / (SF|BR|\(Prime\))$/.test(i.title))).toBe(false)
    expect(check.items.find((i) => i.title === 'The Hobbit' && i.format === 'bluray')).toBeTruthy()
  })
})
